#!/usr/bin/env python3
"""Render the Russian lyric options from lyrics/ru/lines.json.

  python3 tools/ru_lyrics.py            # check stresses + fit, write the Suno .txt files,
                                        # SIDE_BY_SIDE.md and the data block of compare.html
  python3 tools/ru_lyrics.py --check    # only print the fit table

In lines.json an apostrophe after a vowel marks the stressed vowel (ё is always stressed).
The fit table compares each Russian line with the English line it replaces: syllable counts
and whether the line ends on a stressed syllable (the English lines end on held notes, so a
Russian line that ends on a stressed vowel puts that vowel on the long note).
"""
import json, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DIR = ROOT / "lyrics" / "ru"
VOWELS = set("аеёиоуыэюяАЕЁИОУЫЭЮЯ")
FULL = ["A", "B", "C"]


def clean(s):
    return s.replace("'", "")


def accented(s):
    return s.replace("'", "́")


def syllables(s):
    return sum(ch in VOWELS for ch in s)


def ends_stressed(s):
    words = re.findall(r"[А-Яа-яЁё']+", s)
    if not words:
        return False
    w = words[-1]
    if syllables(w) == 1:
        return True
    last = max(i for i, ch in enumerate(w) if ch in VOWELS)
    return w[last] in "ёЁ" or w[last + 1:last + 2] == "'"


def unmarked(s):
    """Multi-syllable words with no stress mark (and no ё)."""
    out = []
    for w in re.findall(r"[А-Яа-яЁё']+", s):
        if syllables(w) > 1 and "'" not in w and not set(w) & set("ёЁ"):
            out.append(w)
    return out


def load():
    return json.loads((DIR / "lines.json").read_text())


def sheet_text(data, pick):
    """pick: unit id -> option key. Returns the Suno lyric sheet."""
    units = {u["id"]: u for u in data["units"]}
    out = []
    for item in data["sheet"]:
        if item[0] == "tag":
            out.append(item[1])
        else:
            _, uid, i = item
            out.append(clean(units[uid][pick[uid]]["lines"][i][0]))
    return "\n".join(out) + "\n"


def fit_rows(data):
    for u in data["units"]:
        for key in data["options"]:
            if key not in u:
                continue
            for i, (ru, gloss) in enumerate(u[key]["lines"]):
                en = u["en"][i]
                yield u["id"], key, i, en, ru


def check(data):
    problems = 0
    print(f"{'unit':6} opt  #  en ru  end  line")
    for uid, key, i, en, ru in fit_rows(data):
        n = syllables(clean(ru))
        end = "✓" if ends_stressed(ru) else "·"
        flag = ""
        if abs(n - en["syl"]) > 3:
            flag = "  <- far from the English count"
        miss = unmarked(ru)
        if miss:
            flag += f"  <- no stress mark: {', '.join(miss)}"
            problems += 1
        print(f"{uid:6} {key}   {i}  {en['syl']:2} {n:2}   {end}   {clean(ru)}{flag}")
    return problems


def side_by_side(data):
    opts = data["options"]
    md = ["# Orbital Sunrise: Russian options, side by side", "",
          "Generated by `tools/ru_lyrics.py` from `lines.json`. Stress is marked with an acute accent "
          "(ё is always stressed). Under each line is a literal back-translation. "
          "`syl` = syllables in the Russian line / in the English line it replaces; "
          "`↓` = the line ends on a stressed syllable, so the stressed vowel gets the held note.", ""]
    for key in FULL:
        o = opts[key]
        md.append(f"* **{key} · {o['ru']}** ({o['name']}). {o['concept']}")
    md.append("")
    for u in data["units"]:
        md.append(f"## {u['label']}" + (f" ({u['sub']})" if u.get("sub") else ""))
        md.append("")
        keys = [k for k in opts if k in u]
        for i, en in enumerate(u["en"]):
            role = f" ({en['role']})" if en.get("role") else ""
            md.append(f"**EN{role}:** {en['t']} · {en['syl']} syl")
            md.append("")
            for k in keys:
                ru, gloss = u[k]["lines"][i]
                n = syllables(clean(ru))
                end = " ↓" if ends_stressed(ru) else ""
                md.append(f"* **{k}** {accented(ru)} · {n}/{en['syl']} syl{end}  \n  _{gloss}_")
            md.append("")
        for k in keys:
            note = u[k].get("note")
            if note:
                md.append(f"> **{k}:** {note}")
                md.append(">")
            for _, q in sorted(u[k].get("ask", {}).items()):
                md.append(f"> **{k}, question for the native speaker:** {q}")
                md.append(">")
        if md[-1] == ">":
            md.pop()
        md.append("")
    return "\n".join(md)


def page_data(data):
    """The JSON embedded in compare.html (stress marks already applied)."""
    d = json.loads(json.dumps(data))
    for u in d["units"]:
        for k in d["options"]:
            if k not in u:
                continue
            u[k]["lines"] = [
                {"ru": accented(ru), "plain": clean(ru), "gloss": g,
                 "syl": syllables(clean(ru)), "end": ends_stressed(ru)}
                for ru, g in u[k]["lines"]]
    d.pop("about", None)
    return d


def main():
    data = load()
    problems = check(data)
    if "--check" in sys.argv:
        sys.exit(1 if problems else 0)
    units = [u["id"] for u in data["units"]]
    for key in FULL:
        text = sheet_text(data, {uid: key for uid in units})
        (DIR / data["options"][key]["file"]).write_text(text)
    (DIR / "SIDE_BY_SIDE.md").write_text(side_by_side(data) + "\n")
    page = DIR / "compare.html"
    if page.exists():
        html = page.read_text()
        blob = json.dumps(page_data(data), ensure_ascii=False, separators=(",", ":"))
        html, n = re.subn(r'(<script id="lyrics-data" type="application/json">).*?(</script>)',
                          lambda m: m.group(1) + blob.replace("</", "<\\/") + m.group(2),
                          html, flags=re.S)
        if n != 1:
            sys.exit("compare.html: lyrics-data block not found")
        page.write_text(html)
    print(f"\nwrote {', '.join(data['options'][k]['file'] for k in FULL)}, SIDE_BY_SIDE.md"
          + (", compare.html" if page.exists() else ""))
    sys.exit(1 if problems else 0)


if __name__ == "__main__":
    main()
